---
#######
# Arr variables
#######
arr_user: "{{ ansible_user }}"
arr_puid: 1000
arr_pgid: 1000
arr_timezone: Europe/Oslo

arr_stack_dir: "/srv/arr"
arr_media_dir: "/home/ubuntu/media"
arr_downloads_dir: "/home/ubuntu/Downloads"

arr_qbittorrent_webui_port: 8080
# true: report corrupt files, false: delete corrupt files and trigger re-download
arr_healarr_dry_run: true
arr_wireguard_conf: "{{ playbook_dir }}/wg0.conf"
